# Generated by Django 2.2.1 on 2019-06-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icc',
            name='matches_lost',
            field=models.IntegerField(default=None),
        ),
    ]
