# Generated by Django 2.2.1 on 2019-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kids', '0002_icc_matches_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icc',
            name='matches_lost',
            field=models.IntegerField(),
        ),
    ]
